Repository cypress-io/cypress, pull requests merged in 2019-12, with the labels that each got.

#5822 Upgrade font-awesome to 5+
  packages/desktop-gui/cypress/integration/project_nav_spec.js
  packages/desktop-gui/cypress/integration/specs_list_spec.js
  packages/desktop-gui/package.json
  packages/desktop-gui/src/app/global-error.jsx
  packages/desktop-gui/src/app/intro.jsx
  packages/desktop-gui/src/app/intro.scss
  packages/desktop-gui/src/app/nav.jsx
  packages/desktop-gui/src/auth/login-form.jsx
  packages/desktop-gui/src/auth/login-modal.jsx
  packages/desktop-gui/src/duration-timer/TimerDisplay.jsx
  packages/desktop-gui/src/lib/utils.js
  packages/desktop-gui/src/project-nav/browsers.jsx
  packages/desktop-gui/src/project-nav/project-nav.jsx
  packages/desktop-gui/src/project/error-message.jsx
  packages/desktop-gui/src/project/onboarding.jsx
  packages/desktop-gui/src/project/warning-message.jsx
  packages/desktop-gui/src/projects/projects-list.jsx
  packages/desktop-gui/src/runs/error-message.jsx
  packages/desktop-gui/src/runs/permission-message.jsx
  packages/desktop-gui/src/runs/project-not-setup.jsx
  packages/desktop-gui/src/runs/runs-list-item.jsx
  packages/desktop-gui/src/runs/runs-list.jsx
  packages/desktop-gui/src/runs/setup-project-modal.jsx
  packages/desktop-gui/src/settings/configuration.jsx
  packages/desktop-gui/src/settings/node-version.jsx
  packages/desktop-gui/src/settings/project-id.jsx
  packages/desktop-gui/src/settings/proxy-settings.jsx
  packages/desktop-gui/src/settings/record-key.jsx
  packages/desktop-gui/src/specs/specs-list.jsx
  packages/desktop-gui/src/styles/vendor.scss
  packages/desktop-gui/src/update/update-banner.jsx
  packages/reporter/package.json
  packages/reporter/src/collapsible/collapsible.tsx
  packages/reporter/src/commands/command.tsx
  packages/reporter/src/errors/an-error.tsx
  packages/reporter/src/header/controls.tsx
  packages/reporter/src/header/header.scss
  packages/reporter/src/header/header.tsx
  packages/reporter/src/header/stats.tsx
  packages/reporter/src/lib/fonts.scss
  packages/reporter/src/runnables/runnables.scss
  packages/reporter/src/test/test.tsx
  packages/runner/package.json
  packages/runner/src/errors/automation-disconnected.jsx
  packages/runner/src/errors/no-automation.jsx
  packages/runner/src/errors/no-spec.jsx
  packages/runner/src/header/header.jsx
  packages/runner/src/header/header.scss
  packages/runner/src/iframe/snapshot-controls.jsx
  packages/runner/src/lib/fonts.scss
  packages/runner/src/selector-playground/selector-playground.jsx
Labels: process: code, type: chore

#5888 use cross-env in npm scripts so they work on Windows
  cli/package.json
  packages/desktop-gui/package.json
  packages/example/package.json
  packages/extension/package.json
  packages/https-proxy/package.json
  packages/launcher/package.json
  packages/runner/package.json
  packages/server/package.json
  packages/socket/package.json
Labels: OS: windows, process: contributing

#5981 Remove packageRules from renovatebot
  renovate.json
Labels: process: dependencies, type: chore

#4827 replace gulp-gh-pages-will with original gulp-gh-pages
  packages/example/gulpfile.js
  packages/example/package.json
Labels: type: dependencies

#6028 remove unused dep 'style-loader'
  packages/web-config/package.json
Labels: process: dependencies

#6039 Typo in the cli readme Markdown header nesting
  cli/README.md
Labels: process: contributing
