Repository cypress-io/cypress, pull requests merged in 2020-11, with the labels that each got.

#8807 fix: rewrite version updater to remove node-webkit-updater dependency
  packages/server/lib/updater.js
  packages/server/package.json
  packages/server/test/unit/updater_spec.js
  yarn.lock
Labels: internal-priority

#9003 feat: Copy to clipboard button for settings/runs in desktop GUI
  packages/desktop-gui/cypress/integration/runs_list_spec.js
  packages/desktop-gui/cypress/integration/settings_spec.js
  packages/desktop-gui/src/runs/runs-list.jsx
  packages/desktop-gui/src/settings/project-id.jsx
  packages/desktop-gui/src/settings/record-key.jsx
  packages/desktop-gui/src/styles/components/_general.scss
Labels: internal-priority

#9059 fix(route2): fixed the issue with not being able to await a request body when providing static response stub
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/net-stubbing/lib/server/intercept-request.ts
Labels: internal-priority

#9081 fix: do not assume valid file info in error stack line
  packages/driver/cypress/fixtures/error-stack-with-http-links.txt
  packages/driver/cypress/integration/cypress/stack_utils_spec.js
  packages/driver/src/cypress/mocha.js
  packages/driver/src/cypress/stack_utils.js
  packages/reporter/cypress/fixtures/cy_command_failed_error.json
  packages/reporter/cypress/fixtures/no_location_app_error.json
  packages/reporter/cypress/integration/test_errors_spec.js
  packages/reporter/src/errors/error-stack.tsx
Labels: internal-priority

#9107 fix: XHR stub error if response json has number/boolean
  packages/driver/cypress/fixtures/boolean.json
  packages/driver/cypress/fixtures/number.json
  packages/driver/cypress/integration/commands/xhr_spec.js
  packages/server/lib/controllers/xhrs.js
Labels: internal-priority

#8499 feat: Support shortcut syntax in cy.type()
  packages/driver/cypress/integration/commands/actions/type_spec.js
  packages/driver/src/cy/keyboard.ts
  packages/driver/src/cypress/error_messages.js
Labels: internal-priority

#9160 fix: prevent crash when selected spec is undefined
  packages/desktop-gui/cypress/integration/specs_list_spec.js
  packages/desktop-gui/src/specs/specs-list.jsx
  packages/desktop-gui/src/specs/specs-store.js
Labels: internal-priority

#9088 feat: include warning when running with invalid config
  packages/server/__snapshots__/cypress_spec.js
  packages/server/lib/cypress.js
  packages/server/lib/errors.js
  packages/server/test/integration/cypress_spec.js
Labels: internal-priority

#9066 feat: Allow type() and click() to select an element inside contenteditable.
  packages/driver/cypress/integration/commands/actions/type_spec.js
  packages/driver/src/cy/actionability.js
  packages/driver/src/dom/elements.ts
  packages/driver/src/dom/selection.ts
Labels: internal-priority, type: breaking change

#9215 feat: deprecate experimentalFetchPolyfill
  packages/server/lib/config_options.ts
  packages/server/lib/errors.js
  packages/server/test/e2e/0_fetch_polyfill_spec.js
  packages/server/test/unit/config_spec.js
Labels: internal-priority

#9239 fix: negated assertions passing w/o existence check
  packages/desktop-gui/cypress/integration/error_message_spec.js
  packages/desktop-gui/cypress/integration/project_nav_spec.js
  packages/desktop-gui/cypress/integration/setup_project_modal_spec.js
  packages/desktop-gui/cypress/integration/specs_list_spec.js
  packages/desktop-gui/cypress/integration/update_modal_spec.js
  packages/desktop-gui/cypress/integration/warning_message_spec.js
  packages/desktop-gui/src/settings/file-preference_spec.jsx
  packages/driver/cypress/integration/commands/assertions_spec.js
  packages/driver/cypress/integration/e2e/focus_blur_spec.js
  packages/driver/src/cy/chai.js
  packages/driver/src/cy/ensures.js
  packages/driver/src/cypress/chai_jquery.js
  packages/reporter/cypress/integration/test_errors_spec.js
  packages/reporter/cypress/support/utils.js
  packages/runner/cypress/integration/retries.ui.spec.js
  packages/ui-components/cypress/integration/file-opener_spec.jsx
Labels: type: breaking change

#9280 feat(net-stubbing): automatically parse JSON req/res bodies
  packages/driver/cypress/fixtures/invalid.json
  packages/driver/cypress/fixtures/json.txt
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/driver/src/cy/net-stubbing/events/request-received.ts
  packages/driver/src/cy/net-stubbing/events/response-received.ts
  packages/driver/src/cy/net-stubbing/events/utils.ts
  packages/net-stubbing/lib/external-types.ts
Labels: internal-priority, type: breaking change

#9281 fix: "RangeError: Index out of range | The value of "offset" is out of range"
  packages/driver/cypress/fixtures/issue-2034.html
  packages/driver/cypress/integration/issues/2034_spec.js
  packages/server/lib/screenshots.js
Labels: internal-priority

#9301 fix(server): CDP needs screencasts ack before sending more frames
  packages/server/lib/browsers/chrome.ts
  packages/server/lib/browsers/cri-client.ts
  packages/server/lib/browsers/electron.js
  packages/server/test/e2e/6_video_compression_spec.js
  packages/server/test/unit/browsers/chrome_spec.js
Labels: internal-priority

#9324 fix: lower-cased HTTP methods can be used with cy.intercept.
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/net-stubbing/lib/server/route-matching.ts
Labels: internal-priority

#8837 feat: add scrollBehavior option
  cli/schema/cypress.schema.json
  cli/types/cypress.d.ts
  cli/types/tests/actions.ts
  packages/desktop-gui/cypress/fixtures/config.json
  packages/driver/cypress/integration/commands/actions/check_spec.js
  packages/driver/cypress/integration/commands/actions/clear_spec.js
  packages/driver/cypress/integration/commands/actions/click_spec.js
  packages/driver/cypress/integration/commands/actions/trigger_spec.js
  packages/driver/cypress/integration/commands/actions/type_spec.js
  packages/driver/src/cy/actionability.js
  packages/driver/src/cy/commands/actions/check.js
  packages/driver/src/cy/commands/actions/click.js
  packages/driver/src/cy/commands/actions/trigger.js
  packages/driver/src/cy/commands/actions/type.js
  packages/driver/src/cypress/utils.js
  packages/server/lib/config_options.ts
  packages/server/test/unit/config_spec.js
Labels: internal-priority
