Repository cypress-io/cypress, pull requests merged in 2020-08, with the labels that each got.

#8153 fix(reporter): minor UI fixes and improvements
  packages/reporter/src/agents/agents.tsx
  packages/reporter/src/commands/commands.scss
  packages/reporter/src/routes/routes.tsx
  packages/reporter/src/runnables/runnables.scss
Labels: internal-priority

#7808 fix: Remove esModuleInterop from ts-node
  packages/server/__snapshots__/1_typescript_support_spec.ts.js
  packages/server/lib/util/ts-node.js
  packages/server/test/e2e/1_typescript_plugins_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-false/cypress.json
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-false/cypress/integration/app_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-false/cypress/plugins/add.js
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-false/cypress/plugins/index.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-false/cypress/support/index.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-false/tsconfig.json
  packages/server/test/unit/project_spec.js
Labels: type: breaking change

#7982 feat: Change default preprocessor to webpack
  .eslintignore
  packages/server/__snapshots__/1_busted_support_file_spec.js
  packages/server/__snapshots__/1_es_modules_spec.js
  packages/server/__snapshots__/1_typescript_support_spec.js
  packages/server/__snapshots__/1_typescript_support_spec.ts.js
  packages/server/__snapshots__/5_spec_isolation_spec.js
  packages/server/__snapshots__/5_stdout_spec.js
  packages/server/__snapshots__/7_record_spec.js
  packages/server/lib/plugins/preprocessor.js
  packages/server/package.json
  packages/server/test/e2e/1_busted_support_file_spec.js
  packages/server/test/e2e/1_es_modules_spec.js
  packages/server/test/e2e/1_typescript_support_spec.ts
  packages/server/test/e2e/4_controllers_spec.js
  packages/server/test/e2e/5_screenshots_spec.js
  packages/server/test/e2e/5_stdout_spec.js
  packages/server/test/integration/http_requests_spec.js
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/es_module_import_failing_spec.js
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/es_modules_in_coffee_spec.coffee
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/typescript_failing_spec.ts
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/typescript_passing_spec.ts
  packages/server/test/support/fixtures/projects/ids/cypress/integration/foo.coffee
  packages/server/test/support/fixtures/projects/no-server/helpers/includes.js
  packages/server/test/support/fixtures/projects/no-server/my-tests/test1.js
  packages/server/test/support/fixtures/projects/ts-proj-with-paths/cypress.json
  packages/server/test/support/fixtures/projects/ts-proj-with-paths/cypress/integration/app_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-paths/src/main.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-paths/tsconfig.json
  packages/server/test/support/helpers/e2e.ts
  packages/server/test/support/helpers/simple_tsify.js
  packages/server/test/unit/plugins/preprocessor_spec.js
  yarn.lock
Labels: internal-priority, type: breaking change

#8143 fix: Remove default esModuleInterop option from ts-node and preprocessor
  .eslintignore
  packages/server/__snapshots__/1_typescript_spec_support_spec.ts.js
  packages/server/lib/plugins/child/run_plugins.js
  packages/server/lib/project.js
  packages/server/lib/util/ts-node-options.js
  packages/server/lib/util/ts-node.js
  packages/server/test/e2e/1_typescript_plugins_spec.ts
  packages/server/test/e2e/1_typescript_spec_support_spec.ts
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/typescript_syntax_error_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-true/cypress.json
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-true/cypress/integration/passing_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-true/cypress/plugins/commonjs-export.js
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-true/cypress/plugins/index.ts
  packages/server/test/support/fixtures/projects/ts-proj-esmoduleinterop-true/tsconfig.json
  packages/server/test/support/fixtures/projects/ts-proj-with-module-esnext/cypress.json
  packages/server/test/support/fixtures/projects/ts-proj-with-module-esnext/cypress/integration/uses_cy_task_in_ts_plugins_file_spec.js
  packages/server/test/support/fixtures/projects/ts-proj-with-module-esnext/cypress/plugins/greeting.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-module-esnext/cypress/plugins/index.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-module-esnext/tsconfig.json
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress.json
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/integration/app_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/integration/js-spec.js
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/integration/math.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/plugins/greeting.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/.eslintrc.json
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/commands.ts
  packages/server/test/support/fixtures/projects/ts-proj-with-own-tsconfig/cypress/support/index.ts
  packages/server/test/support/fixtures/projects/ts-proj/cypress/integration/app_spec.ts
  packages/server/test/support/fixtures/projects/ts-proj/cypress/plugins/commonjs-export-function.js
  packages/server/test/support/fixtures/projects/ts-proj/cypress/plugins/index.ts
  packages/server/test/unit/config_spec.js
  packages/server/test/unit/project_spec.js
Labels: type: breaking change

#8217 fix: Add reporter options
  cli/types/cypress.d.ts
Labels: internal-priority

#8105 fix: Throw error when assertion contains only one language chainer
  packages/driver/cypress/integration/commands/assertions_spec.js
  packages/driver/src/cy/commands/asserting.js
  packages/driver/src/cypress/error_messages.js
Labels: internal-priority

#8424 chore(tests): [internal] fix flake e2e screenshot spec (firefox)
  packages/server/test/e2e/5_screenshots_spec.js
Labels: internal-priority

#8256 fix: Add typing for specType field on spec method
  cli/types/cypress.d.ts
Labels: internal-priority

#8351 fix: remove offscreen mode from headless Electron windows
  packages/server/lib/gui/windows.ts
Labels: internal-priority

#8244 fix: elements with opacity: 0 are not visible
  cli/types/cypress.d.ts
  packages/driver/cypress/fixtures/dom.html
  packages/driver/cypress/fixtures/opacity.html
  packages/driver/cypress/integration/commands/actions/check_spec.js
  packages/driver/cypress/integration/commands/actions/click_spec.js
  packages/driver/cypress/integration/commands/actions/trigger_spec.js
  packages/driver/cypress/integration/commands/actions/type_spec.js
  packages/driver/cypress/integration/dom/visibility_spec.ts
  packages/driver/cypress/integration/e2e/visibility_spec.js
  packages/driver/src/config/jquery.js
  packages/driver/src/cy/ensures.js
  packages/driver/src/dom/visibility.js
Labels: type: breaking change

#8305 feat: can dispatch events with the type they want.
  cli/types/cypress.d.ts
  packages/driver/cypress/fixtures/issue-5650.html
  packages/driver/cypress/integration/commands/actions/trigger_spec.js
  packages/driver/src/cy/commands/actions/trigger.js
  packages/driver/src/cypress/error_messages.js
Labels: internal-priority
