Repository cypress-io/cypress, pull requests merged in 2020-06, with the labels that each got.

#7556 fix flake: waiting_spec, xhr_spec, timers_spec
  packages/driver/test/cypress/integration/commands/waiting_spec.js
  packages/driver/test/cypress/integration/commands/xhr_spec.js
  packages/driver/test/cypress/integration/cy/timers_spec.js
Labels: process: flaky test

#7583 Replace @cypress/underscore.inflection dep
  packages/driver/package.json
  packages/driver/src/config/lodash.d.ts
  packages/driver/src/config/lodash.js
  packages/driver/src/cy/commands/waiting.js
  yarn.lock
Labels: process: dependencies

#7682 fix(types): cy.wait yields previous subject
  cli/types/cypress.d.ts
  cli/types/tests/cypress-tests.ts
Labels: type: typings

#7791 feat(deps): electron@9.0.5
  .node-version
  appveyor.yml
  circle.yml
  package.json
  packages/electron/package.json
  packages/server/__snapshots__/3_issue_173_spec.ts.js
  packages/server/lib/browsers/electron.js
  packages/server/lib/browsers/firefox-util.ts
  packages/server/lib/gui/events.js
  packages/server/lib/gui/windows.js
  packages/server/lib/gui/windows.ts
  packages/server/package.json
  packages/server/test/e2e/3_issue_173_spec.ts
  packages/server/test/support/fixtures/projects/browser-extensions/cypress/integration/spec.js
  packages/server/test/support/fixtures/projects/browser-extensions/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/devtools.html
  packages/server/test/support/fixtures/projects/browser-extensions/devtools-ext/manifest.json
  packages/server/test/unit/browsers/electron_spec.js
  packages/server/test/unit/browsers/firefox_spec.ts
  packages/server/test/unit/gui/events_spec.js
  packages/server/test/unit/gui/windows_spec.ts
  scripts/run-docker-local.sh
  yarn.lock
Labels: type: breaking change

#7790 feat: make cookies have sameSite key by default
  cli/schema/cypress.schema.json
  cli/types/cypress.d.ts
  packages/driver/cypress/integration/commands/cookies_spec.js
  packages/driver/src/cy/commands/cookies.js
  packages/server/__snapshots__/2_cookies_spec.ts.js
  packages/server/__snapshots__/4_request_spec.ts.js
  packages/server/__snapshots__/5_subdomain_spec.ts.js
  packages/server/lib/config.js
  packages/server/lib/errors.js
  packages/server/lib/experiments.ts
  packages/server/test/e2e/2_cookies_spec.ts
  packages/server/test/e2e/4_request_spec.ts
  packages/server/test/e2e/5_subdomain_spec.ts
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/cookies_spec_no_baseurl.coffee
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/request_spec.coffee
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/subdomain_spec.coffee
  packages/server/test/unit/config_spec.js
Labels: type: breaking change

#7650 Drop support for Node 8; Require Node 10+
  circle.yml
  cli/package.json
  packages/driver/cypress/integration/e2e/uncaught_errors_spec.js
  packages/server/package.json
  yarn.lock
Labels: type: breaking change

#7782 Rename uses of term 'whitelist'
  circle.yml
  cli/types/cypress.d.ts
  cli/types/tests/kitchen-sink.ts
  packages/driver/cypress/integration/commands/cookies_spec.js
  packages/driver/cypress/integration/commands/xhr_spec.js
  packages/driver/src/cy/commands/cookies.js
  packages/driver/src/cy/keyboard.ts
  packages/driver/src/cypress/cookies.js
  packages/driver/src/cypress/error_messages.js
  packages/driver/src/cypress/server.js
  packages/example/bin/convert.js
  packages/server/__snapshots__/2_cookies_spec.ts.js
  packages/server/lib/config.js
  packages/server/lib/project.js
  packages/server/lib/saved_state.js
  packages/server/lib/server.js
  packages/server/lib/util/args.js
  packages/server/lib/util/socket_allowed.ts
  packages/server/lib/util/socket_whitelist.ts
  packages/server/test/support/fixtures/projects/cookies/cypress/integration/app_spec.coffee
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/cookies_spec_baseurl.coffee
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/cookies_spec_no_baseurl.coffee
  packages/server/test/unit/args_spec.js
  packages/server/test/unit/saved_state_spec.js
  packages/server/test/unit/screenshots_spec.js
  packages/server/test/unit/server_spec.js
  packages/server/test/unit/util/socket_allowed_spec.ts
  packages/server/test/unit/util/socket_whitelist_spec.ts
Labels: type: breaking change
