Repository cypress-io/cypress, pull requests merged in 2021-04, with the labels that each got.

#15746 docs: update Readme.md
  npm/react/README.md
  npm/react/images/dynamic.gif
  npm/vite-dev-server/README.md
  npm/vue/README.md
  npm/webpack-dev-server/README.md
  yarn.lock
Labels: experiment: component testing

#15769 fix: don't wrap errors thrown by cy.intercept req/res handlers
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/driver/src/cy/net-stubbing/events/before-request.ts
  packages/driver/src/cy/net-stubbing/events/response.ts
  packages/driver/src/cypress/error_messages.js
  packages/runner/cypress/integration/reporter.errors.spec.js
Labels: 7.0 Release

#15835 fix: make "New Spec File" a button link style
  packages/desktop-gui/src/specs/specs-list.jsx
Labels: type: enhancement

#15902 fix(component testing): default config values
  packages/server-ct/src/project-ct.ts
  packages/server/lib/config.js
Labels: component testing

#15885 fix: get next config before requiring devserver
  npm/react/plugins/next/index.js
Labels: component testing, npm: @cypress/react

#15948 fix(tests): Fix server integration test
  packages/server/test/integration/cypress_spec.js
Labels: internal-priority

#15860 chore: Upgrade lodash types
  package.json
  packages/driver/package.json
  yarn.lock
Labels: internal-priority

#15970 chore(component-testing): add pwa plugin to example repo
  npm/vue/examples/vue-cli/cypress/plugins.js
  npm/vue/examples/vue-cli/package.json
  npm/vue/examples/vue-cli/public/img/icons/android-chrome-192x192.png
  npm/vue/examples/vue-cli/public/img/icons/android-chrome-512x512.png
  npm/vue/examples/vue-cli/public/img/icons/android-chrome-maskable-192x192.png
  npm/vue/examples/vue-cli/public/img/icons/android-chrome-maskable-512x512.png
  npm/vue/examples/vue-cli/public/img/icons/apple-touch-icon-120x120.png
  npm/vue/examples/vue-cli/public/img/icons/apple-touch-icon-152x152.png
  npm/vue/examples/vue-cli/public/img/icons/apple-touch-icon-180x180.png
  npm/vue/examples/vue-cli/public/img/icons/apple-touch-icon-60x60.png
  npm/vue/examples/vue-cli/public/img/icons/apple-touch-icon-76x76.png
  npm/vue/examples/vue-cli/public/img/icons/apple-touch-icon.png
  npm/vue/examples/vue-cli/public/img/icons/favicon-16x16.png
  npm/vue/examples/vue-cli/public/img/icons/favicon-32x32.png
  npm/vue/examples/vue-cli/public/img/icons/msapplication-icon-144x144.png
  npm/vue/examples/vue-cli/public/img/icons/mstile-150x150.png
  npm/vue/examples/vue-cli/public/img/icons/safari-pinned-tab.svg
  npm/vue/examples/vue-cli/public/robots.txt
  npm/vue/examples/vue-cli/src/main.js
  npm/vue/examples/vue-cli/src/registerServiceWorker.js
  npm/vue/examples/vue-cli/yarn.lock
Labels: component testing

#16077 chore: Design System Cleanup
  npm/design-system/.storybook/main.js
  npm/design-system/.storybook/preview.js
  npm/design-system/.storybook/reset.scss
  npm/design-system/README.md
  npm/design-system/css.folders.js
  npm/design-system/package.json
  npm/design-system/rollup.config.js
  npm/design-system/src/components/Nav/LeftNav.module.scss
  npm/design-system/src/components/searchInput/SearchInput.stories.tsx
  npm/design-system/src/components/searchInput/SearchInput.tsx
  npm/design-system/src/core/button/Button.module.scss
  npm/design-system/src/core/button/Button.stories.tsx
  npm/design-system/src/core/button/Button.tsx
  npm/design-system/src/core/icon/Icon.stories.tsx
  npm/design-system/src/core/input/IconInput.module.scss
  npm/design-system/src/core/input/IconInput.tsx
  npm/design-system/src/core/input/Input.stories.tsx
  npm/design-system/src/core/input/InputBase.module.scss
  npm/design-system/src/core/input/InputBase.tsx
  npm/design-system/src/core/shared.ts
  npm/design-system/src/core/surface/elevation/Elevation.stories.tsx
  npm/design-system/src/core/surface/elevation/Elevation.tsx
  npm/design-system/src/core/surface/paddedBox/PaddedBox.stories.tsx
  npm/design-system/src/core/surface/paddedBox/PaddedBox.tsx
  npm/design-system/src/core/text/StyledText.stories.tsx
  npm/design-system/src/core/text/StyledText.tsx
  npm/design-system/src/css/baseColors.scss
  npm/design-system/src/css/derived/export.scss
  npm/design-system/src/css/index.scss
  npm/design-system/src/css/semanticColors.scss
  npm/design-system/src/css/spacing.scss
  npm/design-system/src/css/surfaces.scss
  npm/design-system/src/css/typography.scss
  npm/design-system/src/global.scss
  npm/design-system/src/index.scss
  npm/design-system/src/index.ts
  npm/design-system/src/stories/Colors.stories.tsx
  npm/design-system/src/stories/Spacing.stories.tsx
  npm/design-system/src/stories/Surfaces.stories.tsx
  npm/design-system/src/stories/Typography.stories.tsx
  npm/design-system/src/stories/spacing.module.scss
  npm/design-system/src/util/storybook/storyHighlightWrapper/storyHighlightWrapper.module.scss
  npm/design-system/tsconfig.json
  packages/runner-ct/src/app/SpecList/SpecList.module.scss
  packages/runner-ct/src/app/SpecList/SpecList.tsx
  packages/runner-ct/src/variables.scss
  yarn.lock
Labels: design-system

#16099 fix(webpack): allow load custom asset on windows
  npm/webpack-dev-server/src/makeWebpackConfig.ts
Labels: OS: windows, component testing

#16103 fix: make vite-dev-server work on windows
  npm/vite-dev-server/src/makeCypressPlugin.ts
Labels: OS: windows, component testing

#15946 fix: do not treat utf8 requests as binary
  packages/driver/README.md
  packages/driver/cypress/fixtures/utf8-post.html
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/net-stubbing/lib/server/middleware/request.ts
  packages/net-stubbing/lib/server/util.ts
  packages/net-stubbing/test/fixtures/cypress-logo.png
  packages/net-stubbing/test/unit/util-spec.ts
Labels: internal-priority

#15869 fix: cy.then shows wrong type when collection of HTMLElement's is provided
  cli/types/cypress.d.ts
  cli/types/tests/cypress-tests.ts
Labels: internal-priority

#15648 feat(issue-3741): added keyboard support for folder
  packages/desktop-gui/cypress/integration/specs_list_spec.js
  packages/desktop-gui/src/specs/specs-list.jsx
  packages/desktop-gui/src/specs/specs.scss
Labels: internal-priority

#15785 fix: Cypress.cookies.debug() regression
  packages/extension/gulpfile.ts
  packages/extension/webpack.config.js
Labels: internal-priority

#16197 fix(npm/react): support transpiling typescript files in support
  npm/react/examples.env
  npm/react/examples/react-scripts-typescript/cypress.json
  npm/react/examples/react-scripts-typescript/cypress/integration/cy-spec.js
  npm/react/examples/react-scripts-typescript/cypress/plugins/index.js
  npm/react/examples/react-scripts-typescript/cypress/support/index.d.ts
  npm/react/examples/react-scripts-typescript/cypress/support/index.ts
  npm/react/examples/react-scripts-typescript/package.json
  npm/react/examples/react-scripts-typescript/src/App.cy-spec.tsx
  npm/react/examples/react-scripts-typescript/tsconfig.json
  npm/react/plugins/utils/get-transpile-folders.js
Labels: component testing

#16220 fix(vite-dev-server): fix url to the client on win
  npm/vite-dev-server/src/makeCypressPlugin.ts
Labels: OS: windows, component testing

#16237 fix(component-testing): Proper focus ring on SpecList
  npm/design-system/src/core/input/IconInput.tsx
  npm/design-system/src/core/input/Input.stories.tsx
  npm/design-system/src/core/input/Input.tsx
  npm/design-system/src/core/input/InputBase.module.scss
  npm/design-system/src/core/input/InputBase.tsx
  npm/design-system/src/css/derived/export.scss
  npm/design-system/src/css/surfaces.scss
Labels: component testing, design-system

#16215 fix(vite-dev-server): only re-run tests when specs deps are updated
  npm/vite-dev-server/cypress/components/circular-dependencies/a.spec.ts
  npm/vite-dev-server/cypress/components/circular-dependencies/a.ts
  npm/vite-dev-server/cypress/components/circular-dependencies/b.ts
  npm/vite-dev-server/cypress/components/circular-dependencies/c.ts
  npm/vite-dev-server/src/makeCypressPlugin.ts
  npm/vite-dev-server/src/startServer.ts
Labels: component testing

#16257 test: make the design system tests pass
  npm/design-system/package.json
  npm/design-system/src/core/button/Button.module.scss
  npm/design-system/src/css/css-util.scss
  npm/design-system/vite.config.js
  npm/vite-dev-server/package.json
  yarn.lock
Labels: component testing

#16261 fix(npm/react): bump deps and release new version
  npm/react/package.json
  yarn.lock
Labels: component testing

#16280 fix: avoid unmounting React components twice
  npm/mount-utils/src/index.ts
  npm/react/src/mount.ts
Labels: component testing
