Repository cypress-io/cypress, pull requests merged in 2021-03, with the labels that each got.

#15266 fix: nextUntil failure caused by PR 14965
  packages/driver/cypress/fixtures/dom.html
Labels: internal-priority

#15278 chore: Remove jobs that are no longer necessary to run in Circle
  circle.yml
Labels: internal-priority

#15235 fix(net-stubbing): Provide consistent behavior for falsy static responses
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/driver/src/cy/net-stubbing/add-command.ts
  packages/driver/src/cy/net-stubbing/static-response-utils.ts
  packages/net-stubbing/lib/external-types.ts
  packages/net-stubbing/lib/server/util.ts
Labels: type: breaking change

#15444 feat: support ct/e2e specific overrides in cypress.json
  cli/schema/cypress.schema.json
  cli/types/cypress.d.ts
  npm/react/cypress/plugins/index.js
  npm/vue/cypress/plugins/index.js
  packages/server-ct/src/project-ct.ts
  packages/server/lib/open_project.js
  packages/server/lib/plugins/child/run_plugins.js
  packages/server/lib/plugins/index.js
  packages/server/lib/project-e2e.ts
  packages/server/lib/util/settings.js
  packages/server/test/integration/plugins_spec.js
  packages/server/test/support/fixtures/projects/chrome-browser-preferences/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/component-tests/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/firefox-memory/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-before-browser-launch-deprecation/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-config-version/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-config/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-event-deprecated/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/read-only-project-root/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/retries-2/cypress/plugins/index.js
  packages/server/test/unit/settings_spec.js
Labels: internal-priority

#15376 chore: refactor "test recordings" to "test results"
  packages/desktop-gui/src/runs/runs-list.jsx
  packages/server/__snapshots__/7_record_spec.js
  packages/server/lib/errors.js
  packages/server/lib/modes/record.js
  packages/server/test/e2e/7_record_spec.js
Labels: internal-priority

#15415 fix: studio icon displays properly on tests with long title
  packages/reporter/cypress/integration/suites_spec.ts
  packages/reporter/cypress/integration/tests_spec.ts
  packages/reporter/cypress/support/index.ts
  packages/reporter/package.json
  packages/reporter/src/runnables/runnables.scss
  packages/reporter/tsconfig.json
Labels: internal-priority

#15419 fix: Response.headers type.
  cli/types/cypress.d.ts
  cli/types/tests/kitchen-sink.ts
Labels: type: breaking change

#15531 chore: Updated to latest ESLint and updated corresponding plugins
  npm/design-system/src/components/FileExplorer/FileExplorer.tsx
  npm/eslint-plugin-dev/lib/index.js
  npm/eslint-plugin-dev/package.json
  npm/react/.eslintrc
  npm/react/examples/visual-sudoku/src/solver/sudoku.js
  npm/vue/examples/cli/package.json
  npm/webpack-batteries-included-preprocessor/package.json
  npm/webpack-preprocessor/package.json
  package.json
  packages/driver/src/cy/keyboard.ts
  packages/net-stubbing/lib/external-types.ts
  packages/reporter/src/attempts/attempts.tsx
  packages/reporter/src/errors/error-stack.tsx
  packages/reporter/src/lib/file-name-opener.tsx
  packages/reporter/src/main.tsx
  packages/runner-ct/package.json
  packages/runner-ct/src/app/RunnerCt.tsx
  packages/runner-ct/src/app/useScreenshotHandler.tsx
  packages/runner-ct/src/lib/ResizableBox.tsx
  packages/server-ct/crossword-example/unit/App.spec.js
  packages/server-ct/example/cypress/support/commands.js
  packages/server-ct/example/cypress/support/index.js
  packages/server/.eslintrc.json
  packages/server/lib/plugins/dev-server.js
  packages/server/test/e2e/7_record_spec.js
  packages/server/test/support/fixtures/projects/webpack-preprocessor-awesome-typescript-loader/cypress/integration/failing_spec.ts
  packages/server/test/support/fixtures/projects/webpack-preprocessor-ts-loader-compiler-options/cypress/integration/failing_spec.ts
  packages/server/test/support/fixtures/projects/webpack-preprocessor-ts-loader/cypress/integration/failing_spec.ts
  yarn.lock
Labels: internal-priority

#15526 feat: support ct/e2e specific overrides in cypress.json
  cli/schema/cypress.schema.json
  cli/types/cypress.d.ts
  npm/create-cypress-tests/__snapshots__/babel.test.ts.js
  npm/create-cypress-tests/__snapshots__/init-component-testing.test.ts.js
  npm/create-cypress-tests/__snapshots__/next.test.ts.js
  npm/create-cypress-tests/__snapshots__/react-scripts.test.ts.js
  npm/create-cypress-tests/__snapshots__/reactWebpackFile.test.ts.js
  npm/create-cypress-tests/__snapshots__/rollup.test.ts.js
  npm/create-cypress-tests/__snapshots__/vite.test.ts.js
  npm/create-cypress-tests/__snapshots__/vueCli.test.ts.js
  npm/create-cypress-tests/__snapshots__/vueWebpackFile.test.ts.js
  npm/create-cypress-tests/__snapshots__/webpackOptions.test.ts.js
  npm/create-cypress-tests/src/component-testing/babel/babelTransform.test.ts
  npm/create-cypress-tests/src/component-testing/babel/babelTransform.ts
  npm/create-cypress-tests/src/component-testing/templates/_shared/rollup.ts
  npm/create-cypress-tests/src/component-testing/templates/_shared/vite.ts
  npm/create-cypress-tests/src/component-testing/templates/react/babel.ts
  npm/create-cypress-tests/src/component-testing/templates/react/next.ts
  npm/create-cypress-tests/src/component-testing/templates/react/react-scripts.ts
  npm/create-cypress-tests/src/component-testing/templates/react/reactWebpackFile.ts
  npm/create-cypress-tests/src/component-testing/templates/react/webpack-options.ts
  npm/create-cypress-tests/src/component-testing/templates/vue/vueCli.ts
  npm/create-cypress-tests/src/component-testing/templates/vue/vueWebpackFile.ts
  npm/react/cypress/plugins/index.js
  npm/vue/cypress/plugins/index.js
  packages/driver/src/cypress.js
  packages/server-ct/src/project-ct.ts
  packages/server/lib/config_options.ts
  packages/server/lib/open_project.js
  packages/server/lib/plugins/index.js
  packages/server/lib/project-e2e.ts
  packages/server/lib/util/settings.js
  packages/server/lib/util/validation.js
  packages/server/test/integration/plugins_spec.js
  packages/server/test/support/fixtures/projects/chrome-browser-preferences/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/component-tests/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/e2e/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/firefox-memory/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-before-browser-launch-deprecation/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-config-version/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-config/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/plugin-event-deprecated/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/read-only-project-root/cypress/plugins/index.js
  packages/server/test/support/fixtures/projects/retries-2/cypress/plugins/index.js
  packages/server/test/unit/config_spec.js
  packages/server/test/unit/plugins/index_spec.js
  packages/server/test/unit/settings_spec.js
Labels: internal-priority

#15335 feat: create new spec file from desktop-gui
  npm/webpack-preprocessor/package.json
  packages/desktop-gui/cypress/integration/specs_list_spec.js
  packages/desktop-gui/src/lib/ipc.js
  packages/desktop-gui/src/notifications/notification.scss
  packages/desktop-gui/src/specs/specs-list.jsx
  packages/desktop-gui/src/specs/specs-store.js
  packages/desktop-gui/src/specs/specs.scss
  packages/server/__snapshots__/spec_writer_spec.ts.js
  packages/server/lib/gui/dialog.js
  packages/server/lib/gui/dialog.ts
  packages/server/lib/gui/events.js
  packages/server/lib/gui/files.ts
  packages/server/lib/open_project.js
  packages/server/lib/util/spec_writer.ts
  packages/server/test/unit/gui/dialog_spec.js
  packages/server/test/unit/gui/dialog_spec.ts
  packages/server/test/unit/gui/events_spec.js
  packages/server/test/unit/gui/files_spec.ts
  packages/server/test/unit/util/spec_writer_spec.ts
  yarn.lock
Labels: internal-priority

#14543 feat: change cy.intercept override behavior
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/driver/src/cy/commands/querying.js
  packages/driver/src/cy/net-stubbing/add-command.ts
  packages/driver/src/cy/net-stubbing/events/after-response.ts
  packages/driver/src/cy/net-stubbing/events/before-request.ts
  packages/driver/src/cy/net-stubbing/events/index.ts
  packages/driver/src/cy/net-stubbing/events/network-error.ts
  packages/driver/src/cy/net-stubbing/events/response.ts
  packages/driver/src/cy/net-stubbing/static-response-utils.ts
  packages/driver/src/cy/net-stubbing/wait-for-route.ts
  packages/driver/src/cypress/error_messages.js
  packages/driver/src/cypress/events.ts
  packages/driver/types/internal-types.d.ts
  packages/net-stubbing/lib/external-types.ts
  packages/net-stubbing/lib/internal-types.ts
  packages/net-stubbing/lib/server/driver-events.ts
  packages/net-stubbing/lib/server/intercepted-request.ts
  packages/net-stubbing/lib/server/middleware/error.ts
  packages/net-stubbing/lib/server/middleware/request.ts
  packages/net-stubbing/lib/server/middleware/response.ts
  packages/net-stubbing/lib/server/route-matching.ts
  packages/net-stubbing/lib/server/types.ts
  packages/net-stubbing/lib/server/util.ts
  packages/net-stubbing/test/unit/intercepted-request-spec.ts
  packages/net-stubbing/test/unit/route-matching-spec.ts
  packages/proxy/test/integration/net-stubbing.spec.ts
  packages/runner/cypress/fixtures/errors/intercept_spec.ts
  packages/runner/cypress/integration/reporter.errors.spec.js
  packages/server/lib/socket-base.ts
  scripts/binary/zip.js
Labels: type: breaking change

#15647 feat: make cy.intercept url matching more closely match cy.route
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/driver/cypress/integration/commands/xhr_spec.js
  packages/driver/cypress/integration/cy/snapshot_spec.js
  packages/driver/src/cy/net-stubbing/add-command.ts
  packages/net-stubbing/lib/external-types.ts
  packages/net-stubbing/lib/internal-types.ts
  packages/net-stubbing/lib/server/route-matching.ts
  packages/net-stubbing/test/unit/route-matching-spec.ts
  yarn.lock
Labels: internal-priority, type: breaking change

#15651 fix(server): bail out on close if server does not exist
  packages/server/lib/server-base.ts
  packages/server/test/unit/server_spec.js
Labels: internal-priority
