Repository cypress-io/cypress, pull requests merged in 2021-02, with the labels that each got.

#14729 feat(breaking): Remove Cypress.moment()
  cli/package.json
  cli/types/cy-moment.d.ts
  cli/types/cypress.d.ts
  cli/types/index.d.ts
  cli/types/tests/cypress-tests.ts
  packages/desktop-gui/index.d.ts
  packages/driver/cypress/integration/commands/actions/type_errors_spec.js
  packages/driver/cypress/integration/commands/actions/type_spec.js
  packages/driver/cypress/integration/util/moment_spec.js
  packages/driver/package.json
  packages/driver/src/config/moment.js
  packages/driver/src/cy/keyboard.ts
  packages/driver/src/cypress.js
  packages/driver/src/cypress/error_messages.js
  packages/driver/src/cypress/runner.js
  packages/driver/src/cypress/utils.js
  packages/driver/src/main.js
  packages/reporter/index.d.ts
  packages/runner/index.d.ts
  packages/server/test/support/fixtures/projects/e2e/cypress/integration/request_spec.js
  packages/ui-components/index.d.ts
  yarn.lock
Labels: type: breaking change

#14992 fix: include event emitter types from cypress types
  cli/types/cypress-global-vars.d.ts
  cli/types/cypress.d.ts
  cli/types/tests/cypress-tests.ts
Labels: internal-priority

#9077 fix(driver): fixed an issue with tests not failing for scripts with custom window.onerror
  packages/driver/cypress/fixtures/custom-window-onerror.html
  packages/driver/cypress/integration/e2e/uncaught_errors_spec.js
  packages/driver/src/cy/listeners.js
Labels: internal-priority, type: breaking change

#9118 feat(driver): report unhandled rejections using uncaught:exception event
  packages/driver/cypress/fixtures/unhandled-rejection.html
  packages/driver/cypress/integration/e2e/uncaught_errors_spec.js
  packages/driver/src/cy/listeners.js
Labels: type: breaking change

#14643 feat: Throw an error when there's a redirection loop.
  cli/schema/cypress.schema.json
  cli/types/cypress.d.ts
  packages/driver/cypress/fixtures/redirection-loop-a.html
  packages/driver/cypress/fixtures/redirection-loop-b.html
  packages/driver/cypress/integration/commands/navigation_spec.js
  packages/driver/src/cy/commands/navigation.js
  packages/driver/src/cypress/error_messages.js
  packages/server/lib/config_options.ts
  packages/server/test/unit/config_spec.js
Labels: type: breaking change

#15088 fix: update connect to dashboard graphic on runs tab
  packages/desktop-gui/cypress/integration/runs_list_spec.js
  packages/desktop-gui/cypress/integration/setup_project_modal_spec.js
  packages/desktop-gui/src/runs/dashboard-banner.jsx
  packages/desktop-gui/src/runs/project-not-setup.jsx
  packages/desktop-gui/src/runs/runs.scss
  packages/desktop-gui/src/runs/svg-icons.jsx
  packages/desktop-gui/src/styles/components/_empty.scss
Labels: internal-priority

#15129 fix: updated cy.intercept to automatically parse more JSON MIME types
  packages/driver/cypress/integration/commands/net_stubbing_spec.ts
  packages/driver/cypress/plugins/server.js
  packages/driver/src/cy/net-stubbing/events/utils.ts
Labels: type: breaking change

#14769 fix: Show empty jquery Object properly.
  packages/driver/cypress/integration/dom/jquery_spec.ts
  packages/driver/src/cypress/utils.js
Labels: internal-priority

#14965 feat: cy.submit validates inputs before sending data.
  packages/driver/cypress/fixtures/dom.html
  packages/driver/cypress/integration/commands/actions/submit_spec.js
  packages/driver/src/cy/commands/actions/submit.js
  packages/driver/src/cypress/error_messages.js
  yarn.lock
Labels: type: breaking change
