Repository cypress-io/cypress, pull requests merged in 2022-11, with the labels that each got.

#24484 docs: Update @cypress/grep README install instructions
  npm/grep/README.md
Labels: DX

#24601 chore: Skip flaky navigation tests in webkit
  packages/driver/cypress/e2e/commands/navigation.cy.js
Labels: experiment: webkit

#24488 fix: vue2 global directives in component testing
  npm/vue2/src/index.ts
  packages/app/cypress/e2e/runner/reporter-ct-mount-hover.cy.ts
  system-tests/projects/vueclivue2-configured/README.md
  system-tests/projects/vueclivue2-configured/src/components/GlobalComponentWithCustomDirective.vue
  system-tests/projects/vueclivue2-configured/src/components/HelloWorld.cy.js
  system-tests/projects/vueclivue2-configured/src/components/HelloWorld.vue
  system-tests/projects/vueclivue2-configured/src/directive.js
  system-tests/projects/vueclivue2-configured/src/main.js
  tooling/v8-snapshot/cache/dev-linux/snapshot-meta.cache.json
Labels: CT, routed-to-ct

#24592 feat: add warned command state to use for recreated sessions
  packages/driver/cypress/e2e/commands/sessions/sessions.cy.js
  packages/driver/src/cy/commands/sessions/index.ts
  packages/driver/src/cy/commands/sessions/utils.ts
  packages/reporter/cypress/e2e/commands.cy.ts
  packages/reporter/src/commands/command.cy.tsx
  packages/reporter/src/commands/command.tsx
  packages/reporter/src/commands/commands.scss
  packages/reporter/src/errors/errors.scss
  packages/reporter/src/lib/tag.cy.tsx
  packages/reporter/src/lib/tag.scss
  packages/reporter/src/lib/variables.scss
  packages/reporter/src/sessions/sessions-model.ts
  packages/reporter/src/sessions/sessions.cy.tsx
  packages/reporter/src/sessions/sessions.tsx
  packages/reporter/src/sessions/utils.ts
  packages/types/src/driver.ts
Labels: experiment: session
